#ifndef CONSTANTS_H
#define CONSTANTS_H

#include "Vector3.h"

#define SPHERE_DRAG_COEFFICIENT 0.47f
#define HALF_SPHERE_DRAG_COEFFICIENT 0.42f
#define CONE_DRAG_COEFFICIENT 0.5f
#define CUBE_DRAG_COEFFICIENT 1.05f
#define ANGLED_CUBE_DRAG_COEFFICIENT 0.8f
#define LONG_CYLINDER_DRAG_COEFFICIENT 0.82f
#define SHORT_CYLINDER_DRAG_COEFFICIENT 0.82f

#define SPHERE_REFERENCE_AREA Vector3(3.14f, 3.14f, 3.14f)
#define HALF_SPHERE_REFERENCE_AREA Vector3(1.57f, 3.14f, 1.57f)
#define CONE_REFERENCE_AREA Vector3(3.14f, 2.0f, 2.0f)
#define CUBE_REFERENCE_AREA Vector3(4.0f, 4.0f, 4.0f)
#define ANGLED_CUBE_REFERENCE_AREA Vector3(5.67f, 4.0f, 5.67f)
#define LONG_CYLINDER_REFERENCE_AREA Vector3(3.14f, 4.0f, 4.0f)
#define SHORT_CYLINDER_REFERENCE_AREA Vector3(3.14f, 2.0f, 2.0f)

#define AIR_FLUID_DENSITY 1.204f

#define EARTH_GRAVITY_ACCELERATION -9.81f

#endif // !CONSTANTS_H
